name: Test Workflow with Token

on:
  push:
    branches:
      - ci

jobs:
  test-token:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Token (pour debug local, évitez en production)
        run: echo "Token ${{ secrets.GITHUB_TOKEN }}"

      - name: Test avec le token
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
